# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_CifraVirtual(object):
    def setupUi(self, CifraVirtual):
        CifraVirtual.setObjectName("CifraVirtual")
        CifraVirtual.resize(806, 958)
        self.centralwidget = QtWidgets.QWidget(CifraVirtual)
        self.centralwidget.setObjectName("centralwidget")
        self.musicTextDisplay = QtWidgets.QTextEdit(self.centralwidget)
        self.musicTextDisplay.setGeometry(QtCore.QRect(210, 10, 571, 850))
        self.musicTextDisplay.setObjectName("musicTextDisplay")
        self.musicSaveButton = QtWidgets.QPushButton(self.centralwidget)
        self.musicSaveButton.setGeometry(QtCore.QRect(30, 650, 151, 25))
        self.musicSaveButton.setObjectName("musicSaveButton")
        self.musicAddEntryButton = QtWidgets.QPushButton(self.centralwidget)
        self.musicAddEntryButton.setGeometry(QtCore.QRect(30, 680, 151, 25))
        self.musicAddEntryButton.setObjectName("musicAddEntryButton")
        self.musicTimeTrack = QtWidgets.QSlider(self.centralwidget)
        self.musicTimeTrack.setGeometry(QtCore.QRect(220, 870, 551, 20))
        self.musicTimeTrack.setOrientation(QtCore.Qt.Horizontal)
        self.musicTimeTrack.setObjectName("musicTimeTrack")
        self.musicRecording = QtWidgets.QCheckBox(self.centralwidget)
        self.musicRecording.setGeometry(QtCore.QRect(550, 890, 92, 23))
        self.musicRecording.setObjectName("musicRecording")
        self.musicToogleButton = QtWidgets.QPushButton(self.centralwidget)
        self.musicToogleButton.setGeometry(QtCore.QRect(350, 890, 41, 25))
        self.musicToogleButton.setObjectName("musicToogleButton")
        self.musicList = QtWidgets.QListWidget(self.centralwidget)
        self.musicList.setGeometry(QtCore.QRect(30, 10, 151, 631))
        self.musicList.setObjectName("musicList")
        self.musicForwardButton = QtWidgets.QPushButton(self.centralwidget)
        self.musicForwardButton.setGeometry(QtCore.QRect(440, 890, 31, 25))
        self.musicForwardButton.setObjectName("musicForwardButton")
        self.musicLineEntry = QtWidgets.QLineEdit(self.centralwidget)
        self.musicLineEntry.setGeometry(QtCore.QRect(30, 720, 151, 25))
        self.musicLineEntry.setObjectName("musicLineEntry")
        self.musicRewindButton = QtWidgets.QPushButton(self.centralwidget)
        self.musicRewindButton.setGeometry(QtCore.QRect(400, 890, 31, 25))
        self.musicRewindButton.setObjectName("musicRewindButton")
        self.musicReplayButton = QtWidgets.QPushButton(self.centralwidget)
        self.musicReplayButton.setGeometry(QtCore.QRect(480, 890, 31, 25))
        self.musicReplayButton.setObjectName("musicReplayButton")
        CifraVirtual.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(CifraVirtual)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 806, 20))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuOpen = QtWidgets.QMenu(self.menuFile)
        self.menuOpen.setObjectName("menuOpen")
        self.menuEdit = QtWidgets.QMenu(self.menuFile)
        self.menuEdit.setObjectName("menuEdit")
        CifraVirtual.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(CifraVirtual)
        self.statusbar.setObjectName("statusbar")
        CifraVirtual.setStatusBar(self.statusbar)
        self.actionSongs = QtWidgets.QAction(CifraVirtual)
        self.actionSongs.setObjectName("actionSongs")
        self.actionCompositions = QtWidgets.QAction(CifraVirtual)
        self.actionCompositions.setObjectName("actionCompositions")
        self.actionOpenSongs = QtWidgets.QAction(CifraVirtual)
        self.actionOpenSongs.setObjectName("actionOpenSongs")
        self.actionOpenCompositions = QtWidgets.QAction(CifraVirtual)
        self.actionOpenCompositions.setObjectName("actionOpenCompositions")
        self.actionDelete_Song = QtWidgets.QAction(CifraVirtual)
        self.actionDelete_Song.setObjectName("actionDelete_Song")
        self.menuOpen.addAction(self.actionOpenSongs)
        self.menuOpen.addAction(self.actionOpenCompositions)
        self.menuEdit.addAction(self.actionDelete_Song)
        self.menuFile.addAction(self.menuOpen.menuAction())
        self.menuFile.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(CifraVirtual)
        QtCore.QMetaObject.connectSlotsByName(CifraVirtual)

    def retranslateUi(self, CifraVirtual):
        _translate = QtCore.QCoreApplication.translate
        CifraVirtual.setWindowTitle(_translate("CifraVirtual", "CifraVirtual"))
        self.musicSaveButton.setText(_translate("CifraVirtual", "Save"))
        self.musicAddEntryButton.setText(_translate("CifraVirtual", "Add Item"))
        self.musicRecording.setText(_translate("CifraVirtual", "Recording"))
        self.musicToogleButton.setText(_translate("CifraVirtual", ">/#"))
        self.musicForwardButton.setText(_translate("CifraVirtual", "f"))
        self.musicRewindButton.setText(_translate("CifraVirtual", "r"))
        self.musicReplayButton.setText(_translate("CifraVirtual", "R"))
        self.menuFile.setTitle(_translate("CifraVirtual", "File"))
        self.menuOpen.setTitle(_translate("CifraVirtual", "Open"))
        self.menuEdit.setTitle(_translate("CifraVirtual", "Edit"))
        self.actionSongs.setText(_translate("CifraVirtual", "Song"))
        self.actionCompositions.setText(_translate("CifraVirtual", "Composition"))
        self.actionOpenSongs.setText(_translate("CifraVirtual", "Songs"))
        self.actionOpenCompositions.setText(_translate("CifraVirtual", "Compositions"))
        self.actionDelete_Song.setText(_translate("CifraVirtual", "Delete Song"))

