#!/bin/bash

ERR_OUT="$(Ui2Py && python MainThreaded.py 2>&1)"
echo ------ERR_OUT--------
echo "${ERR_OUT}"

FILE_ERROR="$(echo "${ERR_OUT}" | grep --color=always line | tail -n 1)"
echo ------FILE_ERROR----
echo $FILE_ERROR

FILE_ERROR_NAME=$(echo "${FILE_ERROR}" | grep -E -o [a-zA-Z]+\.py)
echo ------FILE_ERROR_NAME----
echo $FILE_ERROR_NAME

FILE_ERROR_LINE="$(echo "${FILE_ERROR}" | sed 's/.*,$/ /g' | grep -E -o "[0-9][0-9]*" | tail -n 1)"
echo ------FILE_ERROR_LINE----
echo "${FILE_ERROR_LINE}"

ID=$(xdotool search --name $FILE_ERROR_NAME)
SEPARATED=$(echo $FILE_ERROR_LINE| sed 's/[0-9]/& /g')
echo -----FILE_ERROR_LINE_SEPARATED----
echo "${SEPARATED}"
xdotool key --window $ID colon $SEPARATED KP_Enter

clear

echo -e "------ERROR ON FILE \e[31m${FILE_ERROR_NAME}\e[39m AT LINE \e[31m${FILE_ERROR_LINE}\e[39m-------"
echo ------ERROR_OUT:------
echo "{$ERR_OUT}"
